linux-build-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling evee via command 'mvn clean install'"
    - git submodule update --init --recursive
    - mvn clean install

linux-test-job:
  stage: test
  tags:
    - linux
  script:
    - cd ~/Downloads/Protege-5.5.0
    - ./run.sh