linux-build-job:
  cache: []
  stage: build
  tags:
    - letheTest
  script:
    - echo "Compiling evee via command 'mvn clean install'"
    - git submodule update --init --recursive
    - mvn clean install -P !complete,letheUpdateTest
    #- mvn help:effective-pom -s settings.xml
    #- mvn help:effective-settings
    #- mvn help:effective-pom -Dverbose
    # - mvn help:effective-settings -s settings.xml
    #- mvn help:effective-pom -Dverbose -s settings.xml
