linux-test-job:
  stage: test
  tags:
    - linux
  script:
    - mkdir ProtegeApplication
    - cd ProtegeApplication
    - git clone https://github.com/protegeproject/protege.git
    - cd protege
    - git checkout v5.5.0
    - mvn clean package -DskipTests=true
    - cd protege-desktop/target/protege-5.5.0-platform-independent
    - ./run.sh
