linux-test-job:
  stage: test
  tags:
    - linux
  script:
    - mkdir ProtegeApplication
    - cd ProtegeApplication
    - git clone https://github.com/protegeproject/protege.git
    - git checkout v5.5.0
    - mvn clean package
