linux-build-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling evee via command 'mvn clean install'"
    - cd lat-scala-dl-tools
    - mvn clean install
    - cd ..
    - mvn clean install

