linux-build-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling EVEE"
    # first step always needs to be updating lat-scala-dl-tools submodule
    - echo "Updating submodules lat-scala-dl-tools and LETHE-0.8"
    - git submodule update --init --recursive --remote
    - echo "Purging local mvn dependency to remove old versions of LETHE"
    - mvn dependency:purge-local-repository -DreResolve=false -DactTransitively=false
    - echo "Compiling via 'mvn clean install'"
    - mvn clean install



# commented out until we fix the problem with headless-mode when starting Protégé on server
#linux-test-job:
#  stage: test
#  tags:
#    - linux
#  script:
#    - git clone https://github.com/protegeproject/protege.git
#    - cd protege
#    - git checkout v5.5.0
#    - mvn clean package -DskipTests=true
#    - cd protege-desktop/target/protege-5.5.0-platform-independent/Protege-5.5.0
#    - dir
