linux-build-job:
  stage: build
  tags:
    - letheTest
  script:
    - jar xvf /lib/de/tu-dresden/inf/lat/lethe-abduction-owlapi4_2.12/0.8-SNAPSHOT/lethe-abduction-owlapi4_2.12-0.8-SNAPSHOT.jar uk/ac/
    - man/cs/lethe/abduction/OWLAbducer.class
    - cd uk/ac/man/cs/lethe/abduction
    # test if the approach is working
    - javap -verbose OWLAbducer.class | grep checkCanceled()
    # actual test
    - javap -verbose OWLAbducer.class | grep getUnsupportedAxiomsEncountered()
