/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tu_dresden_inf_lat_evee_protege_nonEntailment_core_NonEntailmentViewComponent */

#ifndef _Included_de_tu_dresden_inf_lat_evee_protege_nonEntailment_core_NonEntailmentViewComponent
#define _Included_de_tu_dresden_inf_lat_evee_protege_nonEntailment_core_NonEntailmentViewComponent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
