name: build & test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        # cache: maven
    - name: Update submodules
      run:  git submodule update --init --recursive
    - name: Purge local mvn dependency   #to remove old versions of LETHE 
      run: mvn dependency:purge-local-repository -DreResolve=false -DactTransitively=false
    - name: Build with Maven
      run: mvn clean install


